# collections:
#   authors:
#     output: true

url: http://Dormant512.github.io

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      theme: "light"
  - scope:
      path: ""
    values:
      layout: "default"
      base-url: "/"
  - scope:
      path: "index.html"
    values:
      lang: "en"
  - scope:
      path: "about.html"
    values:
      lang: "en"
  - scope:
      path: "ru"
    values:
      lang: "ru"
      base-url: "/ru/"
  - scope:
      path: "de"
    values:
      lang: "de"
      base-url: "/de/"
      
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-paginate-multiple

include: [ru]
include: [de]

paginate_multiple:
  - paginate: 12
    paginate_path: '/page:num/'
    sub_dir: '/en'
  - paginate: 12
    paginate_path: '/ru/page:num/'
    sub_dir: '/ru'
  - paginate: 12
    paginate_path: '/de/page:num/'
    sub_dir: '/de'

# paginate_path: "/page:num/"
